### ISSUE TITLE
Typo 9.5.4 not working

### ISSUE THREAD

**Issue by PeterMeiningen** [vertexvaar/fal_gallery#10]
I installed the new release 3.0.0When I choose "List" in the plugin and choose a Folder - nothing happens.
If I write manually fileadmin/Bilder/ the frontend says "The FAL Gallery Plugin configuration is not correct. Check the List Plugin config. Error: "Unknown Error".
The plugin on the page with in pageview says 
 
 FAL Gallery - List
Default source: >none<
File storage: >none<

I tried also "Datensatzsammlung" where the pics are in, but it doesn´t make any change.
Did I do something wrong?

**Comment by vertexvaar** [comment]
Hi @PeterMeiningen 

i tried to reproduce your described problem but even in a non-composer installation everything works as expected. Please ensure that the folder you choose is selected via the wizard on the right side of the field. See the docs for more info: https://docs.typo3.org/typo3cms/extensions/fal_gallery/Usage/Index.html

Please note that i can not give you free support for your TYPO3 installation. If you need more support you can contact me at support@co-stack.com for a quote.

**Comment by newsdesigner** [comment]
There would be less misunderstanding if the manual had been updated. There is no gallery view anymore.

"The Single View will show the default image.
The List View will show all images from the selected folder.
The Gallery View will show the first image of each subfolder."

For about four years, the same texts. The functions have changed. It was one of the best extensions for galleries. I can understand that you can't provide free support and write a tutorial. However, the last version works differently and therefore there are more questions here than maybe otherwise. For me the singel view doesn't work. In most cases, I'm trying to see if another extension works.

On the Typo3 homepage there should also be a negative rating, then the users could save the unnecessary test. On the Typo3 homepage there should also be a negative rating, then the users could save time for unnecessary tests.

Are we the alpha or beta testers for you?

**Comment by vertexvaar** [comment]
Hello @newsdesigner 

neither the controller actions nor the FlexForm for the plugin view selection has changed in a way that an item or action has been removed or added. It is still the same code as in the first version that was released. Therefore there is no need to update the manual (except for the screenshots maybe).
The functions have *not* changed at all. It's still "gallery", "list" and "single" view. Also the options of each plugin type did not change.

Have you updated your plugin's default folder and image settings to match the new TYPO3 URNs?

> Are we the alpha or beta testers for you?

No you are not. I tested this release as i test any other release. That's why it took some time to actually release this version. I even put some more hours into testing the installation without composer. I don't think you can blame me if it does not work in your environment. Instead if this is really a bug of this extension, please give me more information about what exactly does not work so i can fix it. Bug reports are meant for bug fixing, not venting.

With regards
