### ISSUE TITLE
Add TYPO3 CMS compatibility to version 8.5 and higher

### ISSUE THREAD

**Issue by angeloprevitali** [vertexvaar/fal_gallery#4]
Can you fix the compatibility of your EXT:fal_gallery with the actual TYPO3 CMS version 8.5 and higher?

Thank you very much.

Regards,
Angelo

**Comment by vertexvaar** [comment]
@angeloprevitali Can you provide detailed error messages, so i can check if it will be fixed for you, too?

**Comment by angeloprevitali** [comment]
If I upload your actual version 2.0.0 on a TYPO3 CMS version 8.5.1 I get this message:

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/21805076/844cf952-d732-11e6-8c1c-c8c15fe7676e.png)

**Comment by vertexvaar** [comment]
I understand. But you haven't tried it anyway?
I think except for the wizards (which now use the t3: URN) it should work, so you can check the box und use the plugins if you enter the "default Folder/File" options the old fashioned way. (e.g. "1:/gallery/myGallery/")
The compatibility update is a bigger task (because i will have to validate the t3: URN and need to change a lot of stuff) and it might take some more time.

**Comment by angeloprevitali** [comment]
Ok. Thanks for your infos. What do you mean how long wil you take to adapt the t3: URN for the new TYPO3 for changing this "lot of stuff"?
