### ISSUE TITLE
Question: Changing initial values of default rows amount in Plug-In configuration

### ISSUE THREAD

**Issue by angeloprevitali** [vertexvaar/fal_gallery#6]
Hello Oliver!

We do use your EXT:fal_gallery since a long time now. Now multiple customers asked us if there will be a solution to change the default value of the amount of rows. Initially it has the default value of 5 rows which leads in the Flexform configuration.

Is there any solution how we could adapt the initial default value from the Flexform to i.e. 99 (for 99 rows)?

We tried it with TypoScript in the TS Setup but without any success. Something like 
TCEFORM.tt_content.pi_flexform.falgallery_pi1.general.settings\.cols = 99 but it will not work.

Any ideas?

Thanks for help us out.

Best reagrds,
Angelo

**Comment by vertexvaar** [comment]
Hi @angeloprevitali 

i'm not an expert when it comes to PageTS but i know for sure that you gotta escape the dot between settings and cols, because in FlexForm it will - or at least has been - treated like a string.
Therefore `TCEFORM.tt_content.pi_flexform.falgallery_pi1.general.settings\.cols = 99` will get you closer to the solution, but it does not work either (tested in current TYPO3 master).
I'm sorry but you gotta find that out all by yourself.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 2. Juli 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 3. Juli 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch
