### ISSUE TITLE
Compatibility with TYPO3 Version 8.7.22

### ISSUE THREAD

**Issue by angeloprevitali** [vertexvaar/fal_gallery#8]
Hi Oliver

your great EXT:fal_gallery sin't working with TYPO3 verson 8.7.22 and higher. could you please adapt this? There is just a blank page coming from version 8.7.17 and higher.

Thanks for fixing that.

Best regards,
Angelo

**Comment by vertexvaar** [comment]
Hi @angeloprevitali 

I'll take care of it this evening :slightly_smiling_face:

**Comment by angeloprevitali** [comment]
Thanks Oliver!

just some hints for you: We found out that if we add this line of TypoScript Code in the Page TS the error occures. 

`TCEMAIN.linkHandler {
   folder >
   page {
   }
   file {
      addParams = onclick="jumpToUrl('?act=file&linkAttributes[target]=_blank');return false;" 
   }
   url {
      addParams = onclick="jumpToUrl('?act=url&linkAttributes[target]=_blank');return false;" 
   }
}`

This lines just hides the unneccesary folder and adds the default _blank parameter for adding new PDF, etc. or external URLs.

We didn't found out why it just happens if we add this line of code. There is no other extension that makes some problems.

And btw the T3 version isn't compatible officially with 8.7.x and higher.

Thanks.

Regards,
Angelo

**Comment by vertexvaar** [comment]
Hi @angeloprevitali 

i can not identify any issue with the extension and TYPO3 8.7.22.
The TSConfig you provided is not formatted correctly and if i guess the format the folder selection popup shows an exception. Please check your instance again, as well as the TSConfig.

This issue is closed since it can't be reproduced. If you think otherwise (and you have new hints) let me know.

With regards

**Comment by angeloprevitali** [comment]
Hi Oliver

thanks for checking it. The page TS send isn't wll formatted, right. Here again the correct formatting.

TCEMAIN.linkHandler { 
   folder > 
   file {addParams = onclick="jumpToUrl('?act=file&linkAttributes[target]=_blank');return false;" } 
   url { addParams = onclick="jumpToUrl('?act=url&linkAttributes[target]=_blank');return false;" }
}


Anyway, by installing the extension on a 8.7 version the dependency shows a warning because of 6.2.0-8.6.99. I know it will work with 8.7 but maybe other would appreciate it to know that it really works with 8.7 and higher.

Best regards,
Angelo

**Comment by vertexvaar** [comment]
Hi @angeloprevitali 

TBH i don't think you got the latest version, because in 2.1.2 the dependecy to TYPO3 is [6.2.0 - 8.7.99](https://github.com/vertexvaar/fal_gallery/blob/2.1.2/ext_emconf.php#L16).
I have noticed that i forgot to upload the latest two versions to the TER, so that might be the reason. If you install the extension from TER please consider switching to composer.

Tip: Surround your multiline code with three backticks: ` ``` ` to create a [preformatted multiline code block](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

With regards

**Comment by angeloprevitali** [comment]
Hi Oliver

ahh, thanks. The line formatting that's what i searched for...

Best regards,
Angelo
